package com.community.demo.Model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..notifacation.id
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..notifacation.notifier
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    private Integer notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..notifacation.receiver
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    private Integer receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..notifacation.outer_id
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    private Integer outerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..notifacation.type
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..notifacation.gmt_create
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..notifacation.status
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..notifacation.notifier_name
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    private String notifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..notifacation.outer_title
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    private String outerTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..notifacation.id
     *
     * @return the value of student..notifacation.id
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..notifacation.id
     *
     * @param id the value for student..notifacation.id
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..notifacation.notifier
     *
     * @return the value of student..notifacation.notifier
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public Integer getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..notifacation.notifier
     *
     * @param notifier the value for student..notifacation.notifier
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public void setNotifier(Integer notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..notifacation.receiver
     *
     * @return the value of student..notifacation.receiver
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..notifacation.receiver
     *
     * @param receiver the value for student..notifacation.receiver
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..notifacation.outer_id
     *
     * @return the value of student..notifacation.outer_id
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public Integer getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..notifacation.outer_id
     *
     * @param outerId the value for student..notifacation.outer_id
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public void setOuterId(Integer outerId) {
        this.outerId = outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..notifacation.type
     *
     * @return the value of student..notifacation.type
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..notifacation.type
     *
     * @param type the value for student..notifacation.type
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..notifacation.gmt_create
     *
     * @return the value of student..notifacation.gmt_create
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..notifacation.gmt_create
     *
     * @param gmtCreate the value for student..notifacation.gmt_create
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..notifacation.status
     *
     * @return the value of student..notifacation.status
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..notifacation.status
     *
     * @param status the value for student..notifacation.status
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..notifacation.notifier_name
     *
     * @return the value of student..notifacation.notifier_name
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public String getNotifierName() {
        return notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..notifacation.notifier_name
     *
     * @param notifierName the value for student..notifacation.notifier_name
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public void setNotifierName(String notifierName) {
        this.notifierName = notifierName == null ? null : notifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..notifacation.outer_title
     *
     * @return the value of student..notifacation.outer_title
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..notifacation.outer_title
     *
     * @param outerTitle the value for student..notifacation.outer_title
     *
     * @mbg.generated Thu Feb 13 23:13:59 CST 2020
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle == null ? null : outerTitle.trim();
    }
}