package com.community.demo.Model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..user.ID
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..user.ACCOUNTID
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    private String accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..user.NAME
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..user.TOKEN
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..user.GMTCREATE
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    private Long gmtcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..user.GMTMODIFIED
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    private Long gmtmodified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student..user.picture
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..user.ID
     *
     * @return the value of student..user.ID
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..user.ID
     *
     * @param id the value for student..user.ID
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..user.ACCOUNTID
     *
     * @return the value of student..user.ACCOUNTID
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..user.ACCOUNTID
     *
     * @param accountid the value for student..user.ACCOUNTID
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid == null ? null : accountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..user.NAME
     *
     * @return the value of student..user.NAME
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..user.NAME
     *
     * @param name the value for student..user.NAME
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..user.TOKEN
     *
     * @return the value of student..user.TOKEN
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..user.TOKEN
     *
     * @param token the value for student..user.TOKEN
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..user.GMTCREATE
     *
     * @return the value of student..user.GMTCREATE
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public Long getGmtcreate() {
        return gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..user.GMTCREATE
     *
     * @param gmtcreate the value for student..user.GMTCREATE
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public void setGmtcreate(Long gmtcreate) {
        this.gmtcreate = gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..user.GMTMODIFIED
     *
     * @return the value of student..user.GMTMODIFIED
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public Long getGmtmodified() {
        return gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..user.GMTMODIFIED
     *
     * @param gmtmodified the value for student..user.GMTMODIFIED
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public void setGmtmodified(Long gmtmodified) {
        this.gmtmodified = gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student..user.picture
     *
     * @return the value of student..user.picture
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student..user.picture
     *
     * @param picture the value for student..user.picture
     *
     * @mbg.generated Sat Feb 08 23:42:29 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }
}